---
title: "Replication of Besley and Reynal-Querol (2014, APSR)"
author: 
  - Jeremy Bowles
  - Jessie Bullock
  - Shom Mazumder
date: "March 21, 2016"
output: pdf_document
header_includes:
  - \usepackage{amsmath}
  - \usepackage{setspace}
  - \usepackage{amssymb}
  - \usepackage{graphicx}
  - \usepackage{dcolumn}
  - \usepackage{rotating}
  - \usepackage[utf8]{inputnc}
---
\section{Final Paper Ideas}
For our final paper, we plan to use the latest wave of Afrobarometer survey data to test the effect of historical violence on other indicators of ingroup/outgroup trust and prejudice. We will conduct further robustness checks by transforming the dependent variable to eliminate some of the skewness. One of the things we have noticed is the large number of fixed effects this paper uses for a small n (n=49). We might check for a more parsimonius model and if these fixed effects are all necessary, and to evaluate how few observations can be dropped before the effect disappears.

\include{table_2_replication}

\include{table_3_replication}

\include{table_4_replication}

\include{table_5_replication}

\include{table_6_replication}

\include{table_7_replication}
